### ISSUE TITLE
Correct units in Code table 4.2 discipline 4 category 4 ? 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/GRIB2#145]
# Summary and purpose

Update the units for Cosmic ray neutron flux in Code table 4.2 to align with the units as defined in WMO OSCAR space. (https://space.oscar.wmo.int/variables/view/cosmic_ray_neutron_flux)

<table><tbody><tr><td><strong>Number</strong></td><td><strong>Parameter</strong></td><td><strong>Units</strong></td></tr><tr><td>6</td><td>Cosmic ray neutron flux</td><td><s>/h</s> h-1&nbsp;</td></tr></tbody></table>

# Action proposed

review and verify or fix.

# Discussions

# Detailed proposal

Details of proposal.

**Comment by etoyoda** [comment]
I'm not a specialist in this discipline, but the unit "/h" seems to represent hourly count of neutrons using a kind of sensors like https://en.wikipedia.org/wiki/Neutron_monitor .  If that is the case, it would be better to correct the name of parameter instead of units.  Still I wonder why such a quantity is expressed in GRIB though.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022) notes:

change "/h" to  "h-1"

**Comment by amilan17** [comment]
https://space.oscar.wmo.int/variables/view/cosmic_ray_neutron_flux

**Comment by amilan17** [comment]
@marijanacrepulja - branch is updated

**Comment by marijanacrepulja** [comment]
@amilan17 thanks! I confirm that the branch is updated. We can move this issue to the validated status.
