### ISSUE TITLE
new ocean and ice parameters in Code Table 4.2, Discipline 10

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/GRIB2#222]
### Initial request

The NCEP Environmental Modeling Center requests a new entry in GRIB2 Code Table 4.5 as well as several new parameters in Discipline 10 of GRIB2 Code Table 4.2, for eventual use in the next release update of our Global Forecast System (GFS) model.

### Amendment details

New entry in Code Table 4.5 to accurately depict fixed levels based on density using rho:

Code figure  | Meaning
-- | -- 
172 | Ocean level defined by water density (rho) difference from near-surface to level 

New entries in Code table 4.2, Discipline 10 (Oceanographic products), Category 2 (Ice):

Name | Discipline | Category | Parameter | Units
-- | -- | -- | -- | --
Freezing/melting potential | 10 | 2 | 27 | W m-2
Melt onset date | 10 | 2 | 28 | Numeric
Freeze onset date | 10 | 2 | 29 | Numeric

Note for parameter 28: This is the Julian day of the year that surface melt begins.
Note for parameter 29: This is the Julian day of the year that surface freeze begins.

As an FYI, the proposed numbering for the above parameters begins with 27, since 26 has already been proposed for this same Category in #220

### Requestor(s)

Jeff Ator - U.S. NWS/NCEP/EMC @jbathegit
Andrew Benjamin - U.S. NWS/NCEP/EMC @AndrewBenjamin-NOAA

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code tables 4.2 and 4.5

### Expected impact of change

None

**Comment by sebvi** [comment]
Dear @jbathegit  and @AndrewBenjamin-NOAA ,

I have a couple of comments regarding your proposal. 

1) regarding entries in discipline 10, category 2: I would suggest that you use entries 173 and 175 from Code Table 4.5 in conjonction with your proposed entry 10/2/27 for snow thickness over sea ice. Note that if you are interested in the more accurate snow mass per unit area over sea ice ( m3 m-2 which is also units "m" by cancelation), then you should use entry 10/2/16 . This is more accurate than the physical thickness (what you propose) as it is independent of the snow density. 

2) regarding entries in discipline 10, category 4: we have very similar parameters at ECMWF that we encode using sigma theta instead of rho but with the same density difference of 0.125 and 0.03. You can see them here:

[262114](https://codes.ecmwf.int/grib/param-db/?id=262114)
[262115](https://codes.ecmwf.int/grib/param-db/?id=263115)

Could you check that these are not the same? I know that there are multiple to compute density of sea water depending on temperature, pressure and salinity: rho, sigma, sigma-t, sigma theta, etc.
In any case, if you require specificically "rho", I would suggest that you create a new type of level in code Table 4.5 similar to entries 169, 170 and 171.

**Comment by AndrewBenjamin-NOAA** [comment]
@sebvi I will consult with the requesting developer and provide an update.

**Comment by AndrewBenjamin-NOAA** [comment]
I have collected feedback from several developers and here is what was proposed:

1. Snow thickness (on ice)	(10/2/27):   Will use entry from 10/2/16 

2.  Mixed layer depth (delta rho)    (10/4/52-53)  Received confirmation from the developers that the calculation from the 2 EMCWF fields provided and what is done here are not the same. It was suggested that 10/4/14(water depth) be used in lieu of adding the 2 original fields, with an update to Table 4.5




Here is a revised new parameters list for Code table 4.2, Discipline 10 (Oceanographic products):
Category 2 (Ice):
<html>
<body>


Name | Discipline | Category | Parameter | Units
-- | -- | -- | -- | --
Freezing/melting potential | 10 | 2 | 27 | W m-2
Melt onset date | 10 | 2 | 28 | Numeric
Freeze onset date | 10 | 2 | 29 | Numeric


</body>
</html>


And an additional entry in table 4.5 to accurately depict fixed levels based on density using rho:
<html>
<body>


Name  | Parameter
-- | -- |
Ocean level defined by water density (rho) difference from near-surface to level  | 172


</body>
</html>

**Comment by sebvi** [comment]
following @AndrewBenjamin-NOAA  feedback and proposed changes to the original request, I fully support this proposal.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023 notes: 
Jeff presented the proposal; team agrees to the proposal

**Comment by jbathegit** [comment]
@AndrewBenjamin-NOAA @sebvi

I just started updating this branch in GitHub, and I just wanted to clarify something:

Should the new CT 4.5 entry have a unit of `kg m-3` to match that of existing entry 169 in CT 4.5?  Or is it unitless and should just be listed in the table as `-` for the Unit column?

Please let me know, and sorry that the science behind this is a bit out of my swim lane ;-)

**Comment by AndrewBenjamin-NOAA** [comment]
Good questions @jbathegit. Waiting to hear back from GFS ocean developers, will provide clarification shortly.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
branch still needs to be updated;

**Comment by jbathegit** [comment]
@amilan17 

The [222-new-ocean-and-ice-parameters-in-code-table-42-discipline-10-1](https://github.com/wmo-im/GRIB2/tree/222-new-ocean-and-ice-parameters-in-code-table-42-discipline-10-1) branch has now been updated - thanks!

I just wanted to clarify with the above URL, because it looks like there's also a second duplicate branch [222-new-ocean-and-ice-parameters-in-code-table-42-discipline-10](https://github.com/wmo-im/GRIB2/tree/222-new-ocean-and-ice-parameters-in-code-table-42-discipline-10) (i.e. without the trailing `-1`), and I didn't update that second one.
