### ISSUE TITLE
Template 4.10: Validate Product definition template

### ISSUE THREAD

**Issue by amilan17** [wmo-im/GRIB2#83]
# Branch

https://github.com/wmo-im/GRIB2/tree/issue83

# Summary and purpose

"The UK Met office has an interest in using the GRIB Product definition template 4.10 ( percentile forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval) within the next few months. As you may be aware this is marked as ‘Experimental’ and requires validation before operational status can be granted. We are happy to undertake this role and will seek assistance from other centres in the next few weeks. If we can complete this in time for the deadline we will request its inclusion in FT2021-2." ~ Richard Weedon

**Comment by amilan17** [comment]
@jitsukoh --  I assigned this to you to include in the agenda for next meeting.

**Comment by jitsukoh** [comment]
@richardweedon your request is well noted. What I would like to ask Met Office is that [a new, more generalized template based on PDT 4.10 was proposed by ECMWF in FT2021-1](https://github.com/wmo-im/GRIB2/issues/53) and if Met Office still would like to use PDT 4.10, instead of the new one (PDT 4.87 – Quantile forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval). If it is the case, I am happy to include this request in the agenda of the next meeting to remove the "experimental" status. ECMWF is already using this template (will move to the new one in near future). You can ask volunteers for validation process at the meeting (ECMWF should be able to help but if you are using ecCodes as well it doesn't help) but if there is no one who can help, I will go forward with your sample file and a dump file in text as the proof of a partial validation (that's what we did for PDT 4.87).

**Comment by sebvi** [comment]
ECMWF is happy to assist in the validation

**Comment by amilan17** [comment]
We have a new approach for managing GRIB template notes, please let me know if you have questions.

**Comment by richardweedon** [comment]
I have received word from the team who put forward the requirement to validate this template. The decision has been made to pursue the development of the data using an already operational Product Definition Template. We would therefore request that this issue be closed.

**Comment by jitsukoh** [comment]
@amilan17 @richardweedon as agreed at the meeting, I close this issue.
